apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: quay-sub
spec:
  channel: "quay-v3.5"
  installPlanApproval: Automatic
  name: compliance-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace