apiVersion: v1
kind: Namespace
metadata:
  name: openshift-operators

---

apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: namespace-configuration-operator
  namespace: openshift-operators 
spec:
  channel: alpha
  name: namespace-configuration-operator
  source: community-operators 
  sourceNamespace: openshift-marketplace 