apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "image-registry"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: ocs-external-storagecluster-ceph-rbd
