apiVersion: v1
kind: PersistentVolume
metadata:
  name: test
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
      storage: 100Gi
  volumeType: Filesystem
  storageClassName: ocs-external-storagecluster-ceph-rbd
  persistentVolumeReclaimPolicy: Retain
