apiVersion: v1
kind: Namespace
metadata:
  name: openshift-operators

---

apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-adp-og
  namespace: openshift-adp
spec:
  targetNamespaces:
  - openshift-adp

---

apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-adp-sub
  namespace: openshift-adp
spec:
  channel: "stable" 
  name: redhat-adp-operator
  source: redhat-operators 
  sourceNamespace: openshift-marketplace
