apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: whatever you want
spec:
  secretName: secret_name
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
    - Org_name
  commonName: '*.domain.suffix'
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
  - '*.domain.suffix'
  issuerRef:
    name: issuername
    kind: ClusterIssuer