apiVersion: v1
kind: Namespace
metadata:
  name: quay-container-security

---

apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: quay-container-security
  namespace: quay-container-security
spec:
  targetNamespaces:
  - quay-container-security

---

apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: quay-container-security
  namespace: quay-container-security
spec:
  channel: "stable-3.6"
  installPlanApproval: Automatic
  name: container-security-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace

---

