apiVersion: v1
kind: PersistentVolume
metadata:
  name: image-registry-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
      storage: 200Gi
  nfs:
    path: /mnt/SATA/ocpedgeimgreg
    server: 1.2.3.4
  persistentVolumeReclaimPolicy: Retain
