---
- hosts: localhost
  gather_facts: no
  vars:
    vcenter_server: "vcenter URL"
    vcenter_user: "user with perms"
    vcenter_pass: "user password"
    datacenter_name: "your dc name"
    datastore: "your datastore"
    cluster: "your cluster"
    resource_pool: "your resource pool"
    folder: "your folder"
    isopath: "your path to abm iso"
    netlabel: "your network name"
  tasks:
  - name: Create VM folder
    community.vmware.vcenter_folder:
      hostname: '{{ vcenter_server }}'
      username: '{{ vcenter_user }}'
      password: '{{ vcenter_pass }}'
      datacenter_name: "{{ datacenter_name }}"
      folder_name: "{{ folder }}"
      validate_certs: false
      folder_type: vm
      state: present
    register: vm_folder_creation_result
    delegate_to: localhost

  - name: Add resource pool to vCenter
    community.vmware.vmware_resource_pool:
      hostname: '{{ vcenter_server }}'
      username: '{{ vcenter_user }}'
      password: '{{ vcenter_pass }}'
      datacenter: '{{ datacenter_name }}'
      cluster: '{{ cluster }}'
      resource_pool: '{{ resource_pool }}'
      validate_certs: false
      mem_shares: normal
      mem_limit: -1
      mem_reservation: 0
      mem_expandable_reservations: true
      cpu_shares: normal
      cpu_limit: -1
      cpu_reservation: 0
      cpu_expandable_reservations: true
      state: present
    delegate_to: localhost

  - name: Create Master VMs
    community.vmware.vmware_guest:
      hostname: "{{ vcenter_server }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: false
      datacenter: "{{ datacenter_name }}"
      cluster: "{{ cluster }}"
      resource_pool: "{{ resource_pool }}"
      folder: /{{ datacenter_name }}/vm/{{ folder }}
      name: "{{ item.name }}"
      state: poweredon
      guest_id: rhel8_64Guest
      disk:
      - size_gb: 120
        type: thin
        datastore: "{{ datastore }}"
      hardware:
        version: 15
        boot_firmware: EFI
        memory_mb: 24576
        num_cpus: 4
        scsi: paravirtual
      cdrom:
          - controller_number: 1
            controller_type: sata
            unit_number: 0
            state: present
            type: iso
            iso_path: "{{ isopath }}"
      networks:
      - name: "{{ netlabel }}"
        mac: "{{ item.mac }}"
        ip: "{{ item.ip }}"
        netmask: 255.255.255.0
        device_type: vmxnet3
      wait_for_ip_address: false
    delegate_to: localhost
    register: deploy_vm
    loop:
      - { name: 'master0', mac: '00:50:56:00:00:00', ip: '0.0.0.0' }
      - { name: 'master1', mac: '00:50:56:00:00:00', ip: '0.0.0.0' }
      - { name: 'master2', mac: '00:50:56:00:00:00', ip: '0.0.0.0' }

  - name: Create Worker VMs
    community.vmware.vmware_guest:
      hostname: "{{ vcenter_server }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: false
      datacenter: "{{ datacenter_name }}"
      cluster: "{{ cluster }}"
      resource_pool: "{{ resource_pool }}"
      folder: /{{ datacenter_name }}/vm/{{ folder }}
      name: "{{ item.name }}"
      state: poweredon
      guest_id: rhel8_64Guest
      disk:
      - size_gb: 120
        type: thin
        datastore: "{{ datastore }}"
      - size_gb: 1024
        type: thin
        datastore: "{{ datastore }}"
      hardware:
        version: 15
        boot_firmware: EFI
        memory_mb: 98304
        num_cpus: 16
        scsi: paravirtual
      cdrom:
          - controller_number: 1
            controller_type: sata
            unit_number: 0
            state: present
            type: iso
            iso_path: "{{ isopath }}"
      networks:
      - name: "{{ netlabel }}"
        mac: "{{ item.mac }}"
        ip: "{{ item.ip }}"
        netmask: 255.255.255.0
        device_type: vmxnet3
      - name: "{{ netlabel }}"
        connected: no
        start_connected: no
        device_type: vmxnet3
      wait_for_ip_address: false
    delegate_to: localhost
    register: deploy_vm
    loop:
      - { name: 'worker0', mac: '00:50:56:00:00:00', ip: '0.0.0.0' }
      - { name: 'worker1', mac: '00:50:56:00:00:00', ip: '0.0.0.0' }
      - { name: 'worker2', mac: '00:50:56:00:00:00', ip: '0.0.0.0' }
