apiVersion: v1
kind: Pod
metadata:
  name: nvidia-usage-example-pod
spec:
  containers:
   - name: nvidia-usage-example-pod
     image: nvidia/samples:cuda10.2-vectorAdd
     imagePullPolicy: IfNotPresent
     command: [ "/bin/bash", "-c", "--" ]
     args: [ "while true; do sleep 300000; done;" ]
     resources:
       requests:
         nvidia.com/gpu: 1
       limits:
         nvidia.com/gpu: 1
