apiVersion: v1
kind: Namespace
metadata:
  name: openshift-compliance

---

apiVersion: v1
kind: Namespace
metadata:
  name: openshift-file-integrity

---

apiVersion: v1
kind: Namespace
metadata:
  name: democratic-csi

---

apiVersion: v1
kind: Namespace
metadata:
  name: openshift-storage

---

apiVersion: v1
kind: Namespace
metadata:
  name: openshift-nmstate
