---
- hosts: localhost
  gather_facts: no
  vars:
    vcenter_server: "vcenter.sample.me"
    vcenter_user: "your_deploy_user@vsphere.local"
    vcenter_pass: "enter_password_here"
    datacenter_name: "your_DC_name_here"
    resource_pool: "your_resource_pool_here"
    vcenter_cluster: "your_cluster_name_here"
    vcenter_folder: "your_folder_name_here"
    datastore: "your_datastore_name_here"
  tasks:
  
  - name: Create VM folder
    community.vmware.vcenter_folder:
      hostname: '{{ vcenter_server }}'
      username: '{{ vcenter_user }}'
      password: '{{ vcenter_pass }}'
      datacenter_name: "{{ datacenter_name }}"
      folder_name: "{{ vcenter_folder }}"
      validate_certs: false
      folder_type: vm
      state: present
    register: vm_folder_creation_result
    delegate_to: localhost

  - name: Add resource pool to vCenter
    community.vmware.vmware_resource_pool:
      hostname: '{{ vcenter_server }}'
      username: '{{ vcenter_user }}'
      password: '{{ vcenter_pass }}'
      datacenter: '{{ datacenter_name }}'
      cluster: '{{ vcenter_cluster }}'
      resource_pool: '{{ resource_pool }}'
      validate_certs: false
      mem_shares: normal
      mem_limit: -1
      mem_reservation: 0
      mem_expandable_reservations: true
      cpu_shares: normal
      cpu_limit: -1
      cpu_reservation: 0
      cpu_expandable_reservations: true
      state: present
    delegate_to: localhost

### add dhcp server reservations for acm cluster VMs ###
### add lines to default menu for PXE boot of acm cluster VMs###
### Create loadbalancer VM ####
### Install Packages on loadbalancer VM ###
###  Copy templates to locations on loadbalancer VM ###
###  Modify Templates on loadbalancer VM ###
###  Start Services on loadbalancer VM ###
###  Test Services on loadbalancer VM ###
  
  - name: Create Bootstrap VM
    community.vmware.vmware_guest:
      hostname: "{{ vcenter_server }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: false
      datacenter: "{{ datacenter_name }}"
      cluster: "{{ vcenter_cluster }}"
      resource_pool: "{{ resource_pool }}"
      folder: /{{ datacenter_name }}/vm/{{ vcenter_folder }}
      name: enter_a_name_here
      state: poweredon
      guest_id: rhel8_64Guest
      disk:
      - size_gb: 120
        type: thin
        datastore: "{{ datastore }}"
      hardware:
        version: 15
        boot_firmware: BIOS
        memory_mb: 16384
        num_cpus: 4
        scsi: paravirtual
      networks:
      - name: 172ocp
        mac: 00:50:56:00:00:00
        ip: 0.0.0.0
        netmask: 255.255.255.0
        device_type: vmxnet3
      wait_for_ip_address: false
    delegate_to: localhost
    register: deploy_vm

  - name: Create Master VMs
    community.vmware.vmware_guest:
      hostname: "{{ vcenter_server }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: false
      datacenter: "{{ datacenter_name }}"
      cluster: "{{ vcenter_cluster }}"
      resource_pool: "{{ resource_pool }}"
      folder: /{{ datacenter_name }}/vm/{{ vcenter_folder }}
      name: "{{ item.name }}"
      state: poweredon
      guest_id: rhel8_64Guest
      disk:
      - size_gb: 120
        type: thin
        datastore: "{{ datastore }}"
      hardware:
        version: 15
        boot_firmware: BIOS
        memory_mb: 24576
        num_cpus: 4
        scsi: paravirtual
      networks:
      - name: 172ocp
        mac: "{{ item.mac }}"
        ip: "{{ item.ip }}"
        netmask: 255.255.255.0
        device_type: vmxnet3
      wait_for_ip_address: false
    delegate_to: localhost
    register: deploy_vm
    loop:
      - { name: 'master0', mac: '00:50:56:00:00:00', ip: '0.0.0.0' }
      - { name: 'master1', mac: '00:50:56:00:00:00', ip: '0.0.0.0' }
      - { name: 'master2', mac: '00:50:56:00:00:00', ip: '0.0.0.0' }

  - name: Create Worker VMs
    community.vmware.vmware_guest:
      hostname: "{{ vcenter_server }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: false
      datacenter: "{{ datacenter_name }}"
      cluster: "{{ vcenter_cluster }}"
      resource_pool: "{{ resource_pool }}"
      folder: /{{ datacenter_name }}/vm/{{ vcenter_folder }}
      name: "{{ item.name }}"
      state: poweredon
      guest_id: rhel8_64Guest
      disk:
      - size_gb: 120
        type: thin
        datastore: "{{ datastore }}"
      hardware:
        version: 15
        boot_firmware: BIOS
        memory_mb: 24576
        num_cpus: 4
        scsi: paravirtual
      networks:
      - name: 172ocp
        mac: "{{ item.mac }}"
        ip: "{{ item.ip }}"
        netmask: 255.255.255.0
        device_type: vmxnet3
      wait_for_ip_address: false
    delegate_to: localhost
    register: deploy_vm
    loop:
      - { name: 'ACMworker0', mac: '00:50:56:00:00:00', ip: '0.0.0.0' }
      - { name: 'ACMworker1', mac: '00:50:56:00:0:00', ip: '0.0.0.0' }
      - { name: 'ACMworker2', mac: '00:50:56:00:00:00', ip: '0.0.0.0' }

